baseURL = "http://beachvolleytenerife.netlify.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Soco Beach Volley Club Tenerife"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Soco Beach Volley Club, All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "Training"
weight = 1
[[Languages.en.menu.footer]]
URL = "service"
name = "Camps"
weight = 2
[[Languages.en.menu.footer]]
URL = "pricing"
name = "Prices"
weight = 3
[[Languages.en.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 4
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 5
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "Training"
weight = 2
[[Languages.en.menu.main]]
URL = "service"
name = "Camps"
weight = 3
[[Languages.en.menu.main]]
weight = 4
name = "More"
hasChildren = true
  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"
  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Prices"
  URL = "pricing"
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[Languages.es]
contentDir = "content/spanish"
copyright = "Copyright &copy; 2020 Soco Beach Volley Club"
languageCode = "es-es"
languageName = "Es"
weight = 2
[[Languages.es.menu.footer]]
URL = "about"
name = "Clases"
weight = 1
[[Languages.es.menu.footer]]
URL = "service"
name = "Camps"
weight = 2
[[Languages.es.menu.footer]]
URL = "blog"
name = "Notícias"
weight = 3
[[Languages.es.menu.footer]]
URL = "pricing"
name = "Precios"
weight = 4
[[Languages.es.menu.footer]]
URL = "faq"
name = "Preguntas frecuentes"
weight = 5
[[Languages.es.menu.footer]]
URL = "contact"
name = "Contacto"
weight = 6
[[Languages.es.menu.main]]
URL = "/"
name = "Inicio"
weight = 1
[[Languages.es.menu.main]]
URL = "about"
name = "Clases"
weight = 2
[[Languages.es.menu.main]]
URL = "service"
name = "Camps"
weight = 3
[[Languages.es.menu.main]]
URL = "blog"
name = "Notícias"
weight = 4
[[Languages.es.menu.main]]
weight = 5
name = "Más"
hasChildren = true
  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "Preguntas frecuentes"
  URL = "faq"
  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "Precios"
  URL = "pricing"
[[Languages.es.menu.main]]
URL = "contact"
name = "Contacto"
weight = 6
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML"]
[params]
author = "Cristian Sanz"
contact_form_action = "#"
description = "Tu escuela de voley playa en el Norte de Tenerife"
email = "socobeachvolley@gmail.com"
google_analitycs_id = ""
location = "Playa de María Jiménez, Punta Brava, Puerto de la Cruz"
logo = "images/logo.png"
logo_width = "150px"
phone = "(+34)682539653"
multi_author = false
[params.cookies]
enable = true
expire_days = 2
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "28.410692"
map_longitude = "-16.563478"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
[[params.social]]
icon = "ion-social-instagram-outline"
link = "#"
